name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # run daily at 5:00am (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 13
defaults:
  run:
    shell: bash
jobs:

  #1
  dtc-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "dtc"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #2
  dtc-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "dtc"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #3
  wishbone-tool-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #4
  wishbone-tool-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #5
  wishbone-tool-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #6
  sigrok-cli-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sigrok-cli"
      OS_NAME: "linux"
      SKIP: "true"  # See https://github.com/hdl/conda-misc/issues/29
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #7
  sigrok-cli-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "sigrok-cli"
      OS_NAME: "osx"
      SKIP: "true"  # See https://github.com/hdl/conda-misc/issues/29
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #8
  renode-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "renode"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #9
  renode-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "renode"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils
      - uses: hdl/conda-ci@master

  #10
  renode-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "renode"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #11
  capnproto-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "capnproto"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #12
  capnproto-java-linux:
    runs-on: "ubuntu-20.04"
    needs: "capnproto-linux"
    env:
      PACKAGE: "capnproto-java"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #13
  netlistsvg-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "netlistsvg"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  master-package:
    runs-on: "ubuntu-20.04"
    env:
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: urllib3
      - run: |
          bash .github/scripts/install.sh
          python .github/scripts/wait-for-statuses.py
